server {
    listen 80;
    server_name localhost;

    location / {
        # IMPORTANT: Use this path for Alpine Nginx
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Handle Javascript and CSS files specifically
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|webmanifest)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }
}